# action.yml
name: 'Send Gmail'
description: 'Sends mail with Gmail service'
inputs:
  username:
    description: "Gmail username"
    required: true
  password:
    description: "Gmail password"
    required: true
  recipient:
    description: "recipient"
    required: true
  subject:
    description: "subject"
    required: true
  body:
    description: "body"
    required: true
runs:
  using: "composite"
  steps:
    -
      shell: bash
      run: |
        pwd
        ls -l

