# action.yml
name: 'Send Gmail'
description: 'Sends mail with Gmail service'
inputs:
  username:
    description: "Gmail username"
    required: true
  password:
    description: "Gmail password"
    required: true
  recipient:
    description: "recipient"
    required: true
  subject:
    description: "subject"
    required: true
  body:
    description: "body"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Send Email
      shell: bash
      env:
        USERNAME: $username
        PASSWORD: $password
        RECIPIENT: $recipient
        SUBJECT: $subject
        BODY: $body
      run: python send_gmail.py
